ALTER TABLE public.conventions 
ADD COLUMN IF NOT EXISTS booth_fee DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS accommodation_fee DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS travel_fee DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS food_fee DECIMAL(10,2) DEFAULT 0;
